//go:build generate

/*
Copyright 2025 Olivier Mengué

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:generate go run README_gen.go

package main

import (
	"bytes"
	"fmt"
	"go/doc"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"os/exec"
	"path"
	"strings"
)

// This is a silly README generator that just does
// "go doc . >README.md" in a portable way.
func main() {
	log.SetFlags(0)

	goCmd, err := exec.LookPath("go")
	if err != nil {
		log.Fatal(err)
	}

	cmd := exec.Command(goCmd, "list")
	pkgBytes, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}

	packagePath := strings.TrimSpace(string(pkgBytes))
	name := path.Base(packagePath)
	// TODO follow import rules
	pkgName := strings.TrimSuffix(strings.TrimPrefix(name, "go-"), "-go")
	parts := strings.Split(pkgName, "-")
	pkgName = parts[len(parts)-1]

	f, err := os.Create("README.md")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintf(f, ""+
		"<!-- This file is generated by README_gen.go -->\n"+
		"\n"+
		"# %s\n"+
		"[![GoDoc](https://img.shields.io/badge/godoc-reference-blue.svg)](https://pkg.go.dev/%s)\n"+
		"[![Go Report Card](https://goreportcard.com/badge/%s)](https://goreportcard.com/report/%s)\n"+
		"\n",
		name, packagePath, packagePath, packagePath,
	)

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, ".", nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("Error parsing directory: %v", err)
	}

	var pkg *doc.Package
	for _, p := range pkgs {
		if p.Name == pkgName {
			pkg = doc.New(p, packagePath, 0)
			break
		}
	}

	f.Write(pkg.Markdown(pkg.Doc))
	f.WriteString("\n\n")

	var buf bytes.Buffer

	/*
		for _, c := range pkg.Consts {
			doc.ToText(&buf, fmt.Sprintf("const (%s)", c.Doc), "        ", "", 80)
			for _, n := range c.Names {
				buf.WriteString(fmt.Sprintf("\n%s", n))
			}
			buf.WriteString("\n\n")
		}

		for _, t := range pkg.Types {
			doc.ToText(&buf, fmt.Sprintf("type %s %s", t.Name, t.Doc), "        ", "", 80)
			for _, c := range t.Consts {
				doc.ToText(&buf, fmt.Sprintf("const (%s)", c.Doc), "        ", "", 80)
				for _, n := range c.Names {
					buf.WriteString(fmt.Sprintf("\n%s", n))
				}
				buf.WriteString("\n\n")
			}

			for _, v := range t.Vars {
				doc.ToText(&buf, fmt.Sprintf("var (%s)", v.Doc), "        ", "", 80)
				for _, n := range v.Names {
					buf.WriteString(fmt.Sprintf("\n%s", n))
				}
				buf.WriteString("\n\n")
			}

			for _, f := range t.Funcs {
				buf.Write(pkg.Markdown(f.Doc))
				fmt.Fprintf("## `func %s`\n\n%s", f.Name, f.Doc), "        ", "", 80)
				buf.WriteString("\n\n")
			}

			for _, m := range t.Methods {
				doc.ToText(&buf, fmt.Sprintf("func (%s) %s %s", m.Recv, m.Name, m.Doc), "        ", "", 80)
				buf.WriteString("\n\n")
			}

		}

		for _, v := range pkg.Vars {
			doc.ToText(&buf, fmt.Sprintf("var (%s)", v.Doc), "        ", "", 80)
			for _, n := range v.Names {
				buf.WriteString(fmt.Sprintf("\n%s", n))
			}
			buf.WriteString("\n\n")
		}
	*/

	for _, f := range pkg.Funcs {
		buf.WriteString("## `")
		printer.Fprint(&buf, fset, f.Decl)
		buf.WriteString("`\n")
		buf.Write(pkg.Markdown(f.Doc))
		buf.WriteString("\n\n")
	}

	fmt.Fprintln(f, buf.String())
}
